### ISSUE TITLE
OS environment variables are ignored when (unrelated) environment variables are defined in playbook

### ISSUE THREAD

**Issue by RobinR1** [passbolt/lab-passbolt-ansible-collection#13]
I've configured the Passbolt ansible lookup plugin using OS environment variables set by AWX. This works without problem unless there is a `environment:` block defined in the ansible play, even when no passbolt plugin related variables are set in that block.

Example:
Environment variables are set on OS level and available to the Ansible process:
```bash
PASSBOLT_BASE_URL
PASSBOLT_PRIVATE_KEY
PASSBOLT_PASSPHRASE
```
And with that, this works correctly:
```yaml
- name: Test passbolt
  host: localhost
  tasks:
    - name: Lookup predefined resource
      ansible.builtin.debug:
        msg: "Password resource 1 is: {{ lookup('anatomicjc.passbolt.passbolt', 'Ansible predefined test resource').password }}"
```
However, this fails:
```yaml
- name: Test passbolt
  host: localhost
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  tasks:
    - name: Lookup predefined resource
      ansible.builtin.debug:
        msg: "Password resource 1 is: {{ lookup('anatomicjc.passbolt.passbolt', 'Ansible predefined test resource').password }}"
```
with:
```
Error was a <class 'ValueError'>, original message: Expected: ASCII-armored PGP data.
```

So it seems that the plugin fails to look up the OS environment variables whenever there is a `environment:` block defined in the play.

Looking at the code in function 
https://github.com/passbolt/lab-passbolt-ansible-collection/blob/ec035d465d98daf89c5d84bf67057807358d4dd4/plugins/lookup/passbolt.py#L104-L117
I think the OS environment is completely ignored when `environment_variables` is set even when the required variable is not found inside `environment_variables`.
I'm not familiar enough with Python and Ansible libraries to quickly create a pull request for this, but I think the code should fall back to the OS environment when the required variable is not found in `environment_variables` .
