### ISSUE TITLE
Plugin not found

### ISSUE THREAD

**Issue by br0nsky** [passbolt/lab-passbolt-ansible-collection#3]
Hi, I tried using the Ansible lookup plugin but it appears it can't find it even though it seems to be installed properly. I tried following[ this article](https://blog.passbolt.com/managing-secrets-in-ansible-using-passbolt-87af031ceab6) but no luck.

- Python version: 3.10.6
- Galaxy collection version : 0.0.6
- py-passbolt version: 0.0.9
- Ansible version: 2.13.5
- Ubuntu version : 22.04

Here is my task : 
```
- ansible.builtin.command: "{{ lookup('passbolt', 'test') }}"
  environment:
    PASSBOLT_BASE_URL: "https://passbolt.domain.com"
    PASSBOLT_PRIVATE_KEY: "{{ lookup('ansible.builtin.file', '~/private_key') }}"
    PASSBOLT_PASSPHRASE: "XXXXXXXXXX"
```
I tried `"{{ lookup(passbolt, 'test') }}"` , `"{{ lookup('passbolt', 'test') }}"`,`"{{ lookup('anatomicjc.passbolt', 'test') }}"` etc. but it kept giving me this error : 

`{"msg": "lookup plugin (passbolt) not found"}`

Do you have an idea ?

Thanks in advance.
